# Generated by Django 5.2.12 on 2026-03-17 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_message', models.TextField(verbose_name='Mensaje del usuario')),
                ('bot_response', models.TextField(verbose_name='Respuesta del bot')),
                ('intent', models.CharField(default='desconocida', max_length=50, verbose_name='Intención detectada')),
                ('confidence', models.FloatField(default=0.0, verbose_name='Nivel de confianza')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
            ],
            options={
                'verbose_name': 'Conversación',
                'verbose_name_plural': 'Conversaciones',
                'ordering': ['-created_at'],
            },
        ),
    ]
